### PR TITLE
Linkify dbgmodel docs

### PR DESCRIPTION
**Pull request by jazzdelightsme**
This change adds 301 links in 159 files. The links were added by a
powershell script that did the following:

1. Determine a list of topics: the sum of the <topicName> portions of all
   files named nn-whatever-&lt;topicName&gt;.md.

2. For each file in the dbgmodel directory, determine what portions of
   the file should NOT get linkified:
   * The YAML frontmatter.
   * Markdown headings.
   * HTML tables.
   * Code blocks.
   * Existing links.

3. Search through each file for references to the topic names (except
   for the "self" topic; i.e. don't look for IFoo in
   nn-whatever-ifoo.md).

4. For each match that is not in an off-limits portion of the file,
   replace the topic reference with a link.

I'll attach the script that I used in a comment to this PR.

### CODE REVIEW

**Comment by jazzdelightsme** [comment]
Content of my Linkify.ps1 script:

```powershell
<#
.SYNOPSIS
    Updates Windows documentation .md files to add links to other topics in the same directory. A "topic" is the <topicName> from every file named nn-whatever-<topicName>.md file in the current directory.
#>
[CmdletBinding( DefaultParameterSetName = 'OutputDirParameterSet' )]
param( [Parameter( Mandatory = $true, Position = 0, ParameterSetName = 'OutputDirParameterSet' )]
       [string] $OutputDir,

       [Parameter( Mandatory = $true, Position = 0, ParameterSetName = 'InplaceParameterSet' )]
       [switch] $UpdateFilesInPlace,

       [Parameter( Mandatory = $false, Position = 1 )]
       [string] $Path = '*.md'
     )

try
{
    if( !$OutputDir -and !$UpdateFilesInPlace )
    {
        throw "I need either an output dir or permission to update files in place."
    }

    if( $OutputDir )
    {
        $null = mkdir $OutputDir -ErrorAction ignore
    }

    Add-Type -TypeDefinition @'
namespace danthom {
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

// Represents a list of Span objects (index, length, description). Allows you to query
// whether a given index is contained within any of the contained spans.
public class Spans
{
    public struct Span
    {
        public readonly string Description;
        public readonly uint   Index;
        public readonly uint   Length;

        public Span( string description, uint index, uint length )
        {
            Description = description;
            Index       = index;
            Length      = length;
        }

        public bool IsZeroLength
        {
            get { return Length == 0; }
        }

        public bool ContainsIndex( uint index )
        {
            return (index >= Index) && (index < (Index + Length));
        }

        public override string ToString()
        {
            return String.Format( CultureInfo.InvariantCulture,
                                  "[{0}]({1}, {2})",
                                  Description,
                                  Index,
                                  Length );
        }
    }


    private List< Span > m_ranges = new List< Span >();


    public void AddSpan( string description, uint start, uint length )
    {
        m_ranges.Add( new Span( description, start, length ) );
    }

    public bool ContainsIndex( uint index )
    {
        foreach( var span in m_ranges )
        {
            if( span.ContainsIndex( index ) )
            {
                return true;
            }
        }
        return false;
    }

    public IEnumerable< Span > IndexContainedBy( uint index )
    {
        foreach( var span in m_ranges )
        {
            if( span.ContainsIndex( index ) )
            {
                yield return span;
            }
        }
    }

    public override string ToString()
    {
        StringBuilder sb = new StringBuilder( m_ranges.Count * 15 );
        foreach( var span in m_ranges )
        {
            sb.AppendLine( span.ToString() );
        }
        return sb.ToString();
    }
} // end class Spans
} // end namespace
'@

    function GetTopicName( [string] $fileName )
    {
        return [regex]::match( $fileName, 'nn-.*-(?<topicName>.*)\.md' ).Groups[ 'topicName' ].Value
    }


    # TODO: uh... we should probably take an input dir, too
    $topicFiles = dir nn-*

    $topics = $topicFiles | %{
        $topicFile = $_.Name
        $topicName = GetTopicName $topicFile

        [PSCustomObject] @{
            'TopicFile' = $topicFile
            'TopicName' = $topicName
        }
    }

    if( !$topics )
    {
        Write-Error "You need to run this from the directory that contains the topics that you want to link to."
        return
    }

    Write-Host ''
    Write-Host 'Greetings. Your topics are:' -Fore Yellow
    Write-Host ('    ' + [string]::Join( "`n    ", $topics.TopicName )) -Fore Cyan
    Write-Host ''


    # Returns the number of links added.
    function LinkifyTopics( $file )
    {
        $selfTopic = GetTopicName $file

        $content = Get-Content -Raw $file

        [danthom.Spans] $offLimitsRegions = [danthom.Spans]::new()


        #
        # First category of off-limit content: the YAML front matter:
        #

        $m = [regex]::Match( $content, '^---\r?\n(.*\r?\n)*^---', 'MultiLine' )

        if( !$m.Success )
        {
            Write-Warning "missing yaml? file: $file"
        }

        $offLimitsRegions.AddSpan( 'yaml', $m.Index, $m.Length )


        #
        # Second category of off-limit content: headings
        #

        $ms = [regex]::Matches( $content, '^#.*$', 'MultiLine' )

        foreach( $m in $ms )
        {
            $offLimitsRegions.AddSpan( 'heading', $m.Index, $m.Length )
        }


        #
        # Third category of off-limit content: tables
        #

        $ms = [regex]::Matches( $content, '<table>.*</table>', 'SingleLine' )

        foreach( $m in $ms )
        {
            $offLimitsRegions.AddSpan( 'table', $m.Index, $m.Length )
        }
        # Actually... if there were two tables, then we probably got three matches, which
        # would be bad (both individual tables, plus the first <table> to the second
        # table's </table>). But I don't think any of the topics I'm working with have
        # multiple tables.
        if( $ms.Count -gt 1 )
        {
            Write-Warning "multiple tables not handled well! file: $file"
        }


        #
        # Fourth category of off-limit content: code blocks
        #

        # There's probably some fancy-pants regex that can handle this, but I don't know
        # it off the top of my head, so we're going to handle fenced code block like so:
        [int] $index = 0
        [int] $index2 = 0
        while( ($index = $content.IndexOf( '```', $index2 )) -ge 0 )
        {
            $index2 = $content.IndexOf( '```', $index + 3 )

            if( $index2 -lt 0 )
            {
                throw "unmatched '``````' at index $index of $file"
            }
            $index2 += 3 # for the '```' itself
            $offLimitsRegions.AddSpan( 'code', $index, ($index2 - $index) )
        }


        #
        # Fifth category of off-limit content: existing links
        #

        $ms = [regex]::Matches( $content, '\[[^][]+\]\([^\(\)]+\)', 'SingleLine' )

        foreach( $m in $ms )
        {
            $offLimitsRegions.AddSpan( 'link', $m.Index, $m.Length )
        }

     #  Write-Host "OffLimitsRegions for $file : " -Fore magenta
     #  Write-Host $offLimitsRegions.ToString()

        [int] $newLinks = 0
        $matchesAndTopics = [System.Collections.Generic.List[PSCustomObject]]::new()

        foreach( $topic in $topics )
        {
            # Don't create links to yourself:
            if( $topic.TopicName -eq $selfTopic )
            {
                continue
            }

            # Note that we have to add the word boundary anchors, so that IFoo does not
            # match with IFoo2, for example.
            $ms = [regex]::Matches( $content, ('\b' + $topic.TopicName + '\b'), 'IgnoreCase' )

            foreach( $m in $ms )
            {
                $matchesAndTopics.Add( [PSCustomObject] @{ 'Match' = $m ; 'Topic' = $topic } )
            }
        } # end foreach( $topic )


        # Now we need to sort by match index so that we can zip through the file content,
        # replacing as we go.
        $matchesAndTopics.Sort( {
            param( $left, $right )

            return $left.Match.Index.CompareTo( $right.Match.Index )
        } )


        $sb = [System.Text.StringBuilder]::new( $content.Length * 2 )
        [int] $sourceReadIndex = 0

        foreach( $matchAndTopic in $matchesAndTopics )
        {
            $m     = $matchAndTopic.Match
            $topic = $matchAndTopic.Topic

            if( !$offLimitsRegions.ContainsIndex( $m.Index ) )
            {
                $newLinks++

                $null = $sb.Append( $content, $sourceReadIndex, $m.Index - $sourceReadIndex ).
                            Append( '[' ).
                            Append( $m.Value ). # use $m.Value instead of $topic.TopicName so that case is preserved
                            Append( ']' ).
                            Append( '(' ).
                            Append( $topic.TopicFile ).
                            Append( ')' )

                $sourceReadIndex = $m.Index + $m.Length

              # Write-Host "linkifying at index: $($m.index)"
            }
            else
            {
              # Write-Host "Not considering match at index $($m.Index) because: $($offLimitsRegions.IndexContainedBy( $m.Index ).Description)" -Fore Cyan
            }
        }

        # Don't forget the end...
        $null = $sb.Append( $content, $sourceReadIndex, ($content.Length - $sourceReadIndex) )
        $content = $sb.ToString()

        # Time to write the linkified content back out.
        if( $OutputDir )
        {
            $newPath = Join-Path $OutputDir $file.Name
        }
        else
        {
            $newPath = $file.FullName
        }

        Set-Content -Path $newPath -Value $content -NoNewline

        return $newLinks
    } # end LinkifyTopics()


    $files = @( Get-ChildItem -Path $Path )

    [int] $i = 0
    [int] $totalLinksAdded = 0
    [int] $totalFilesChanged = 0
    foreach( $file in $files )
    {
        Write-Progress -Activity 'Linkifying...' `
                       -CurrentOp $file `
                       -PercentComplete (($i / $files.Count) * 100) `
                       -Status "Processing file $($i + 1) of $($files.Count)"

        $linksAdded = LinkifyTopics $file

        if( $linksAdded -gt 0 )
        {
            $totalFilesChanged++
            $totalLinksAdded += $linksAdded
        }
        $i++
    }

    Write-Host "Total links added: $totalLinksAdded" -Fore Cyan
    Write-Host "Total files changed: $totalFilesChanged" -Fore Cyan
}
finally { }
```

**Review by DOMARS — APPROVED** [review]
@jazzdelightsme - This looks great! Having the links to related dbgmodel topics really improves the docs. Thanks for the good work here!

**Comment by DOMARS** [comment]
Adding minor follow up notes for pre-existing markdown chars, such as pointer that may need clean up.

```
dbgmodel bindreadonlyproperty 

A pointer-to-member function pointer of signature (PCWSTR, [IModelObject](nn-dbgmodel-imodelobject.md) *, [IModelObject](nn-dbgmodel-imodelobject.md)**) which will act as the getter for the newly created read-only property accessor.

dbgmodel idebughoststatus polluserinterruptd 

dbgmodel imodelobject getkey
```
Update this link:

```
dbgmodel-idatamodelconcept

[IModelObject](nn-dbgmodel-imodelobject.md)::SetConcept.
```

**Comment by DOMARS** [comment]
@EliotSeattle - This PR is ready to go to master/live when you have a moment.

**Comment by DOMARS** [comment]
@barrygolden - Eliot is preparing for vacation, so can you push this up to master/live?

**Pull request merged**
