### PR TITLE
Add link to structure

### PR DESCRIPTION
**Pull request by hsebs**
#728

### CODE REVIEW

**Review by lorihollasch — CHANGES_REQUESTED** [review]
@hsebs, thanks for submitting this work for #738! Can you fix HTML link end to be </a> and resubmit?

**Comment by hsebs** [comment]
@lorihollasch , Thanks to your review. 
I found that my markdown parser could not distinguish the end of the tag.

**Review by lorihollasch — APPROVED** [review]
@hsebs, looks great. Thanks again!

**Comment by lorihollasch** [comment]
#728

**Pull request merged**
