### PR TITLE
Update ns-ntifs-_security_descriptor.md

### PR DESCRIPTION
**Pull request by hsebs**
* Add description for members
* Fix link to ZwQuerySecurityObject and ZwSetSecurityObject
* Convert html to Markdown

### CODE REVIEW

**Review by lorihollasch — COMMENTED** [review]
Yikes, thanks for reporting the missing member descriptions, @hsebs! Where did you get your descriptions from? I ask because, on quick glance, I'm seeing more than one Revision value.

**Comment by hsebs** [comment]
@lorihollasch 
I refered [InitializeSecurityDescriptor](https://docs.microsoft.com/windows/win32/api/securitybaseapi/nf-securitybaseapi-initializesecuritydescriptor) Page and [RtlCreateSecurityDescriptor](https://docs.microsoft.com/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlcreatesecuritydescriptor) Page to write description of revision. They says "The revision level to assign to the security descriptor. This parameter must be SECURITY_DESCRIPTOR_REVISION.". 

So, I added the sentence that "This value should be SECURITY_DESCRIPTOR_REVISION."

I didn't know that there are more than one value for revision field. (In WDK10, there is only one value.)


I get information of the other fields from comment of `_SECURITY_DESCRIPTOR_RELATIVE` in ntifs.h. In self-relative format, a security descriptor stores a `_SECURITY_DESCRIPTOR_RELATIVE` structure instead of `_SECURITY_DESCRIPTOR` structure. (I confirmed it with my test code.) But offsets of some fields are different from offsets in `_SECURITY_DESCRIPTOR`.  

So, I added note that "This member might be invalid.".

Thank you for reviewing my commit.

**Comment by hsebs** [comment]
I get information of fields might be invalid from comment of _SECURITY_DESCRIPTER_RELATIVE in ntifs.h.

**Comment by hsebs** [comment]
I removed the sentence that "This value should be SECURITY_DESCRIPTOR_REVISION."

**Review by lorihollasch — APPROVED** [review]
@hsebs , thanks for this PR that fills in the blanks. I might make a few additions to the page, depending on what I find internally. Really appreciate your commitment to bettering the docs.

**Pull request merged**
