### PR TITLE
Mark IOCTL_HID_ACTIVATE_DEVICE and IOCTL_HID_DEACTIVATE_DEVICE as obsolete

### PR DESCRIPTION
**Pull request by AndrewYangMSFT**

### CODE REVIEW

**Comment by AndrewYangMSFT** [comment]
FYI, the commit for IOCTL_HID_ACTIVATE_DEVICE was named as IOCTL_HID_DEACTIVATE_DEVICE. The actual change is right.

**Comment by Roodalf2020** [comment]
Andrew, is this something I need to do? Or is this a reference?

**Comment by AndrewYangMSFT** [comment]
Thanks Roodalf2020. I didn't find a quick way to correct the commit message. This PR has two commits. If completing the PR will stash both commits and just leave the final PR comment in github, I believe we're fine. Otherwise, if you could let me know how to correct the commit message, that would be great.

Thanks,
Andrew

**Comment by billlattimer** [comment]
@AndrewYangMSFT , @Roodalf2020 I'll push a final commit from your branch with the corrected descriptions. I'm just checking the language guidance in our publishing guide.

**Comment by billlattimer** [comment]
@AndrewYangMSFT I'm going to close the PR and email a review link with terminology that better aligns with the Docs content guidelines.

**Pull request closed without merging**
