### PR TITLE
Update nf-fwpsk-fwpsopentoken0.md

### PR DESCRIPTION
**Pull request by keith-horton**
Added a critical detail - that the calling process must have a special privilege (SE_DEBUG_NAME) enabled in their process token in order to be able to call this API.

### CODE REVIEW

**Comment by aviviano** [comment]
@keith-horton - Is it ok if we move this detail to a separate remarks section?

## -remarks
The process that calls <b>fwpsopentoken0</b> must have the SE_DEBUG_NAME privilege enabled in its process token.

**Comment by keith-horton** [comment]
> @keith-horton - Is it ok if we move this detail to a separate remarks section?
> 
> ## -remarks
> The process that calls fwpsopentoken0 must have the SE_DEBUG_NAME privilege enabled in its process token.

Yep, that sounds good to me!
Sorry, I wasn't sure where to insert that text.

**Comment by aviviano** [comment]
> > @keith-horton - Is it ok if we move this detail to a separate remarks section?
> > ## -remarks
> > The process that calls fwpsopentoken0 must have the SE_DEBUG_NAME privilege enabled in its process token.
> 
> Yep, that sounds good to me! Sorry, I wasn't sure where to insert that text.

No worries! Opening PRs is a huge help, thanks so much for helping us keep these topics updated!

**Comment by keith-horton** [comment]
> > > @keith-horton - Is it ok if we move this detail to a separate remarks section?
> > > ## -remarks
> > > The process that calls fwpsopentoken0 must have the SE_DEBUG_NAME privilege enabled in its process token.
> > 
> > 
> > Yep, that sounds good to me! Sorry, I wasn't sure where to insert that text.
> 
> No worries! Opening PRs is a huge help, thanks so much for helping us keep these topics updated!

The change looks good. Thank you for jumping on these so quickly!

**Pull request merged**
