### PR TITLE
typo: seperate -> separate

### PR DESCRIPTION
**Pull request by nschonni**
Not sure if the typo is in the product though

### CODE REVIEW

**Comment by EliotSeattle** [comment]
Thanks, @nschonni 
@domars, can you verify whether or not the typo is in the header file?

**Comment by DOMARS** [comment]
Sadly, the spelling error is in the header, so we won't be able to fix this typo in the docs.

```
typedef struct _FEATURE_DATA_CD_AUDIO_ANALOG_PLAY {
    FEATURE_HEADER Header;
    UCHAR SeperateVolume           : 1;
    UCHAR SeperateChannelMute      : 1;```

**Review by DOMARS — COMMENTED** [review]
Sadly, the spelling error is in the header, so we won't be able to fix this typo in the docs.

**Comment by nschonni** [comment]
Product bug FTW 😛

**Pull request closed without merging**
