### PR TITLE
US 1974660: Previous versions cleanup - part 26

### PR DESCRIPTION
**Pull request by craigcaseyMSFT**
Project to clean up the previous versions for "Driver Reference" articles. Next set of files being moved to wdk-ddi, for image, print, and sd technologies.

### CODE REVIEW

**Comment by craigcaseyMSFT** [comment]
Hi @barrygolden  - Moved over from previous-versions. Please let me know if everything looks OK to merge. Thanks!

**Review by ghost — COMMENTED** [review]
The StiCreateInstanceW topic has example code in the remarks section. For optimal formatting, should probably unindent and add a code fence. For example:

```cpp

<code sample>

```

All else looks good.

**Comment by ghost** [comment]
Thanks, Craig!

The StiCreateInstanceW topic has example code in the remarks section. For optimal formatting, should probably unindent and add a code fence. For example:

```cpp

<code sample>

```

All else looks good.

**Review by ghost — APPROVED** [review]
Looks good!

**Comment by craigcaseyMSFT** [comment]
Everything reviewed and approved

#sign-off

**Pull request merged**
